services:
  pocket-piano-web:
    image: git.rodydavis.dev/rodydavis/the-pocket-piano:latest
    restart: unless-stopped
    expose:
      - "80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3